/** Common ingredients for local search-as-you-type suggestions. */
export const INGREDIENT_SUGGESTIONS = [
  'all-purpose flour',
  'almond flour',
  'almond milk',
  'apple',
  'apple cider vinegar',
  'avocado',
  'bacon',
  'baking powder',
  'baking soda',
  'banana',
  'basil',
  'bay leaf',
  'beef broth',
  'bell pepper',
  'black beans',
  'black pepper',
  'blueberries',
  'bread',
  'broccoli',
  'brown sugar',
  'butter',
  'buttermilk',
  'cabbage',
  'canned tomatoes',
  'carrot',
  'cauliflower',
  'celery',
  'cheddar cheese',
  'chicken breast',
  'chicken broth',
  'chicken thigh',
  'chickpeas',
  'chili powder',
  'chocolate chips',
  'cilantro',
  'cinnamon',
  'cocoa powder',
  'coconut milk',
  'coconut oil',
  'coriander',
  'corn',
  'cornstarch',
  'cream cheese',
  'cucumber',
  'cumin',
  'curry powder',
  'dill',
  'egg',
  'eggplant',
  'evaporated milk',
  'feta cheese',
  'fish sauce',
  'flour',
  'fresh ginger',
  'garlic',
  'ginger',
  'granulated sugar',
  'grape tomatoes',
  'green beans',
  'green onion',
  'ground beef',
  'ground turkey',
  'half and half',
  'heavy cream',
  'honey',
  'hot sauce',
  'kale',
  'ketchup',
  'kidney beans',
  'lemon',
  'lemon juice',
  'lentils',
  'lettuce',
  'lime',
  'lime juice',
  'maple syrup',
  'mayonnaise',
  'milk',
  'mint',
  'mozzarella',
  'mushroom',
  'mustard',
  'nutmeg',
  'oat milk',
  'oats',
  'olive oil',
  'onion',
  'orange juice',
  'oregano',
  'paprika',
  'parmesan',
  'parsley',
  'pasta',
  'peanut butter',
  'pecans',
  'pineapple',
  'pita bread',
  'potato',
  'powdered sugar',
  'pumpkin puree',
  'quinoa',
  'red onion',
  'red wine vinegar',
  'rice',
  'ricotta',
  'rolled oats',
  'rosemary',
  'salmon',
  'salt',
  'sesame oil',
  'sesame seeds',
  'shallot',
  'shrimp',
  'sour cream',
  'soy sauce',
  'spinach',
  'strawberries',
  'sugar',
  'sweet potato',
  'thyme',
  'tomato',
  'tomato paste',
  'tomato sauce',
  'tortilla',
  'turmeric',
  'vanilla extract',
  'vegetable broth',
  'vegetable oil',
  'walnuts',
  'water',
  'white rice',
  'white vinegar',
  'whole milk',
  'wine',
  'yeast',
  'yogurt',
  'zucchini',
] as const;

export const QUANTITY_UNITS = [
  'g',
  'kg',
  'ml',
  'L',
  'tsp',
  'tbsp',
  'cup',
  'oz',
  'lb',
  'piece',
  'clove',
  'slice',
  'bunch',
  'pinch',
  'can',
  'packet',
] as const;
